// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDeliverObjects.Objects
{
    public partial class Location
    {
        public Location()
        {
            MerchantBranches = new HashSet<MerchantBranch>();
        }

        public long Id { get; set; }
        public string Address { get; set; }
        public int CountryId { get; set; }
        public string City { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime ModifiedDate { get; set; }
        public DateTime CreationDate { get; set; }

        public virtual Country Country { get; set; }
        public virtual ICollection<MerchantBranch> MerchantBranches { get; set; }
    }
}