// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDeliverObjects.Objects
{
    public partial class Merchant
    {
        public Merchant()
        {
            MerchantBranches = new HashSet<MerchantBranch>();
        }

        public long Id { get; set; }
        public long OrganizationId { get; set; }
        public string MerchantName { get; set; }
        public string Overview { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public bool? IsActive { get; set; }
        public DateTime ModifiedDate { get; set; }
        public DateTime CreationDate { get; set; }

        public virtual Organization Organization { get; set; }
        public virtual ICollection<MerchantBranch> MerchantBranches { get; set; }
    }
}