// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDeliverObjects.Objects
{
    public partial class MerchantEmployee
    {
        public long Id { get; set; }
        public long EnrolmentId { get; set; }
        public long MerchantBranchId { get; set; }
        public string NationalNumber { get; set; }
        public string ProfilePicture { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public bool? IsActive { get; set; }
        public DateTime ModifiedDate { get; set; }
        public DateTime CreationDate { get; set; }

        public virtual Enrolment Enrolment { get; set; }
        public virtual MerchantBranch MerchantBranch { get; set; }
    }
}