// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDeliverObjects.Objects
{
    public partial class MerchantBranch
    {
        public MerchantBranch()
        {
            MerchantEmployees = new HashSet<MerchantEmployee>();
        }

        public long Id { get; set; }
        public long MerchantId { get; set; }
        public string BranchName { get; set; }
        public string Overview { get; set; }
        public string BranchPicture { get; set; }
        public long LocationId { get; set; }
        public string Address { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public bool? IsActive { get; set; }
        public DateTime ModifiedDate { get; set; }
        public DateTime CreationDate { get; set; }

        public virtual Location Location { get; set; }
        public virtual Merchant Merchant { get; set; }
        public virtual ICollection<MerchantEmployee> MerchantEmployees { get; set; }
    }
}