// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDeliverObjects.Objects
{
    public partial class Organization
    {
        public Organization()
        {
            Merchants = new HashSet<Merchant>();
            OrganizationEmployees = new HashSet<OrganizationEmployee>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public string Timezone { get; set; }
        public int CountryId { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public bool? IsActive { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime ModifiedDate { get; set; }

        public virtual Country Country { get; set; }
        public virtual ICollection<Merchant> Merchants { get; set; }
        public virtual ICollection<OrganizationEmployee> OrganizationEmployees { get; set; }
    }
}